# Example auth config

# user twoips can access from two specific IPs
# example bearer token for test is base64('twoips:token:secret') = 'dHdvaXBzOnRva2VuOnNlY3JldA=='
twoips:
  - "1.2.3.0/24"
  - "4.5.6.7/32"

# user largeblock can access from the whole 20-bit CIDR.
# example bearer token for test is base64('largeblock:token:secret') = 'bGFyZ2VibG9jazp0b2tlbjpzZWNyZXQ='
largeblock:
  - "172.16.0.0/12"

# user noaccess can not access from anywhere
# example bearer token for test is base64('noaccess:token:secret') = 'bm9hY2Nlc3M6dG9rZW46c2VjcmV0'
noaccess: []

# user everywhere can access from any IP
# example bearer token for test is base64('everywhere:token:secret') = 'ZXZlcnl3aGVyZTp0b2tlbjpzZWNyZXQ='
everywhere: ["0.0.0.0/0"]

# Update value with local docker network gateway
# example bearer token for test is base64('dockerhostuser:token:secret') = 'ZG9ja2VyaG9zdHVzZXI6dG9rZW46c2VjcmV0'
dockerhostuser: ["172.18.0.1/32"]
